name: Build llama.cpp for Android

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [armeabi-v7a, arm64-v8a, x86, x86_64]

    steps:
      # 1. Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # 4. Install NDK 28.2.13676358
      - name: Install NDK 28.2.13676358
        run: sdkmanager --install "ndk;28.2.13676358"

      # 5. Configure environment variable
      - name: Set ANDROID_NDK_HOME
        run: echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/28.2.13676358" >> $GITHUB_ENV

      # 6. Configure CMake
      - name: Configure CMake
        run: |
          cmake -B build-${{ matrix.abi }} \
          -DCMAKE_BUILD_TYPE=Release \
          -DANDROID_ABI=${{ matrix.abi }} \
          -DANDROID_PLATFORM=android-24 \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DLLAMA_CURL=OFF

      # 7. Build
      - name: Build
        run: cmake --build build-${{ matrix.abi }} -j

      # 8. Upload Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: llama-${{ matrix.abi }}
          path: build-${{ matrix.abi }}/*.so
